version: '3.8'

services:
  postgresql:
    image: postgres:16.0-alpine
    container_name: iot-test-problem_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD:  ${PG_PASSWORD:-postgres}
      POSTGRES_DB:        ${PG_DB:-iot_test_problem}
      POSTGRES_USER:      ${PG_USER:-postgres}
    volumes:
      - ./tmp/pg-data:/var/lib/postgresql/data
      - ./docker/postgresql/init-scripts/:/docker-entrypoint-initdb.d/
    #TODO(Kharlamov): Add healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres} -d ${PG_DB:-iot_test_problem}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s