version: '3.8'

services:
  postgresql:
    image: postgres:16.0-alpine
    container_name: iot-test-problem_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD:  ${PG_PASSWORD:-postgres}
      POSTGRES_DB:        ${PG_DB:-iot_test_problem}
      POSTGRES_USER:      ${PG_USER:-postgres}
    volumes:
      - ./tmp/pg-data:/var/lib/postgresql/data
    #TODO(Kharlamov): Add healthcheck